site:
  name: 'Bruno Chagas &mdash; Front-end Developer'

  locales: [en]

  seo_title: Bruno Chagas - Front-end Developer
  meta_keywords: "some meta keywords"
  meta_description: "some meta description"

  pages:
    - "index":
        title: "Home page"
        published: true
        listed: false

    - "about":
        title: "About"
        publisher: true

    - "work":
        title: "Work"
        published: true

    - "articles":
        title: "Articles"
        published: true

    - "contact":
        title: "Contact"
        published: true

    - "404":
        title: "Page not found"
